import type { APIRoute } from 'astro';
import { supabase } from '../../../../lib/supabase.ts';
import { getSessionUser } from '../../../../lib/session.ts'; // <--- CORRECTED import
import type { Project } from '../../../../lib/database.types';

export const POST: APIRoute = async ({ request }) => {
  try {
    const user = await getSessionUser(); // <--- CORRECTED: Use getSessionUser
    if (!user) { return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401 }); }

    const body = await request.json();
    const { title, description, image_url, category_id, is_published, display_order } = body;

    const newProject: Partial<Project> = {
        title,
        description: description || null,
        image_url: image_url || null,
        category_id: category_id || null,
        is_published: is_published === true,
        display_order: parseInt(display_order) || 0,
        created_at: new Date().toISOString(), // Add created_at explicitly if not autogenerated
        updated_at: new Date().toISOString()
    };

    const { data, error } = await supabase.from('projects').insert([newProject]).select().single();

    if (error) throw error;
    return new Response(JSON.stringify(data), { status: 201 });
  } catch (error: any) {
    console.error("API Error - Create Project:", error.message);
    return new Response(JSON.stringify({ error: error.message }), { status: 500 });
  }
};